### ISSUE TITLE
Complete Readme.

### ISSUE THREAD

**Issue by jsroyal** [sonatype/sisu-guice#13]
Please complete readme file so it will help for newbie.

**Comment by cstamas** [comment]
@jsroyal SISU is an eclipse project, it has some (short) doco here:
https://www.eclipse.org/sisu/docs/tutorials/index.html

**Comment by mcculls** [comment]
As @cstamas said, the local [README.md](https://github.com/sonatype/sisu-guice/blob/master/README.md) explains this is a patched build of Google Guice

For more information about Google Guice see their [README.md](https://github.com/google/guice/blob/master/README.md) and [User Guide](https://github.com/google/guice/wiki/Motivation)
