### ISSUE TITLE
Update Readme file

### ISSUE THREAD

**Issue by jsroyal** [sonatype/sisu-guice#14]
Please provide more info about sisu-guice project. So it will help to every body basic overview about this project.

**Comment by mcculls** [comment]
The existing README is clear that this is a patched build of the [Google Guice](https://github.com/google/guice/) project. The exact list of patches that have been applied can be found in the [PATCHES](https://github.com/sonatype/sisu-guice/tree/master/PATCHES) subdirectory. The README also covers [compatibility](https://github.com/sonatype/sisu-guice#compatibility-with-google-guice) with the original project.

For all other information you should refer to the original [Google Guice](https://github.com/google/guice/) project, including its [README](https://github.com/google/guice/blob/master/README.md).
