### ISSUE TITLE
Deploy a maven artifact

### ISSUE THREAD

**Issue by chrisbaron** [sonatype/sisu-guice#15]
Hi,

It seems like the last release to maven was version 3.2.6.  Are there any plans to do another release of the current version?

Thanks,
Chris

**Comment by mcculls** [comment]
I'm hoping to sort out a release this weekend for https://github.com/sonatype/sisu-guice/issues/17

**Comment by jvanzyl** [comment]
Awesome!

**Comment by mcculls** [comment]
sisu-guice [4.2.0](http://repo1.maven.org/maven2/org/sonatype/sisu/sisu-guice/4.2.0/) is now available on central - this is based on Google Guice 4.2.0 plus some [patches](https://github.com/sonatype/sisu-guice/tree/sisu-guice-4.2.0/PATCHES)
