### ISSUE TITLE
Update to guice 4.2.0

### ISSUE THREAD

**Issue by petergeneric** [sonatype/sisu-guice#17]
Guice 4.2.0 is out now with support for Java 9, could we get an ETA on a sisu-guice release of 4.2.0 please?

**Comment by mcculls** [comment]
Sure, I'll try to sort out a release this weekend

**Comment by mcculls** [comment]
sisu-guice [4.2.0](http://repo1.maven.org/maven2/org/sonatype/sisu/sisu-guice/4.2.0/) is now available on central - this is based on Google Guice 4.2.0 plus some [patches](https://github.com/sonatype/sisu-guice/tree/sisu-guice-4.2.0/PATCHES)
